export default function SectionPreview({ type }) {
    const bg = { hero: 'bg-gradient-to-br from-slate-800 to-blue-900', stats: 'bg-gradient-to-r from-blue-600 to-indigo-600', cta: 'bg-gradient-to-br from-blue-600 to-indigo-700', contact: 'bg-slate-900', expertise: 'bg-slate-800' };
    const previews = {
        hero: (<div className="flex h-full items-center gap-2 px-3"><div className="flex-1 space-y-1"><div className="h-2 w-16 rounded bg-white/80" /><div className="h-1.5 w-24 rounded bg-white/40" /><div className="mt-1.5 flex gap-1"><div className="h-2.5 w-10 rounded bg-blue-400" /><div className="h-2.5 w-8 rounded bg-white/30" /></div></div></div>),
        about: (<div className="flex h-full items-center gap-2 px-3"><div className="flex-1 space-y-1"><div className="h-1.5 w-10 rounded bg-blue-400/60" /><div className="h-2 w-20 rounded bg-slate-300" /><div className="h-1 w-16 rounded bg-slate-200" /></div><div className="h-8 w-10 rounded bg-slate-200" /></div>),
        services: (<div className="flex h-full items-center justify-center gap-1.5 px-3">{[1,2,3].map(i => <div key={i} className="h-8 w-8 rounded border border-slate-200 bg-white p-1"><div className="h-2 w-2 rounded bg-blue-300" /><div className="mt-1 h-1 w-full rounded bg-slate-200" /></div>)}</div>),
        stats: (<div className="flex h-full items-center justify-center gap-3 px-3">{[1,2,3].map(i => <div key={i} className="text-center"><div className="mx-auto h-2.5 w-6 rounded bg-white/80" /><div className="mt-0.5 h-1 w-8 rounded bg-white/40" /></div>)}</div>),
        testimonials: (<div className="flex h-full items-center justify-center gap-1.5 px-3">{[1,2,3].map(i => <div key={i} className="h-9 w-9 rounded border bg-white p-1"><div className="flex gap-px">{[1,2,3,4,5].map(s => <div key={s} className="h-1 w-1 rounded-full bg-amber-400" />)}</div><div className="mt-1 h-0.5 w-full rounded bg-slate-200" /></div>)}</div>),
        gallery: (<div className="grid h-full grid-cols-3 gap-0.5 p-2">{[1,2,3,4,5,6].map(i => <div key={i} className="rounded bg-slate-200" />)}</div>),
        image_compare: (<div className="flex h-full items-center px-3"><div className="flex h-8 w-full overflow-hidden rounded"><div className="w-1/2 bg-slate-300" /><div className="w-px bg-blue-500" /><div className="w-1/2 bg-blue-100" /></div></div>),
        cta: (<div className="flex h-full items-center justify-center"><div className="text-center"><div className="mx-auto h-2 w-20 rounded bg-white/80" /><div className="mx-auto mt-1 h-1.5 w-14 rounded bg-white/40" /><div className="mx-auto mt-1.5 h-2.5 w-12 rounded bg-white/70" /></div></div>),
        faq: (<div className="flex h-full flex-col justify-center gap-1 px-3">{[1,2,3].map(i => <div key={i} className="flex items-center gap-1 rounded border border-slate-200 bg-white px-1.5 py-0.5"><div className="h-1 flex-1 rounded bg-slate-200" /><span className="text-[6px] text-slate-400">+</span></div>)}</div>),
        contact: (<div className="flex h-full items-center gap-2 px-3"><div className="flex-1 space-y-1"><div className="h-2 w-12 rounded bg-white/70" /><div className="h-1 w-16 rounded bg-white/40" /></div><div className="h-9 w-14 rounded border border-white/20 bg-white/10 p-1 space-y-0.5"><div className="h-1 w-full rounded bg-white/30" /><div className="h-1 w-full rounded bg-white/30" /><div className="h-2 w-full rounded bg-blue-400/60" /></div></div>),
        pricing: (<div className="flex h-full items-center justify-center gap-1.5 px-3">{[1,2,3].map(i => <div key={i} className={"h-10 w-8 rounded border bg-white p-1 " + (i===2 ? 'border-blue-400 ring-1 ring-blue-200' : 'border-slate-200')}><div className="h-1 w-full rounded bg-slate-200" /><div className="mt-0.5 h-1.5 w-4 rounded bg-slate-300" /></div>)}</div>),
        team: (<div className="flex h-full items-center justify-center gap-2 px-3">{[1,2,3,4].map(i => <div key={i} className="text-center"><div className="mx-auto h-4 w-4 rounded-full bg-slate-200" /><div className="mt-0.5 mx-auto h-0.5 w-4 rounded bg-slate-300" /></div>)}</div>),
        blog_list: (<div className="flex h-full items-center justify-center gap-1.5 px-3">{[1,2,3].map(i => <div key={i} className="h-9 w-9 rounded border border-slate-200 bg-white p-1"><div className="h-3 w-full rounded bg-slate-100" /><div className="mt-0.5 h-1 w-full rounded bg-slate-200" /></div>)}</div>),
        slider: (<div className="flex h-full items-center px-3"><div className="relative h-8 w-full rounded bg-slate-200 overflow-hidden"><div className="absolute inset-y-0 left-0 w-3/4 bg-gradient-to-r from-slate-300 to-transparent" /><div className="absolute bottom-1 left-2 h-1.5 w-10 rounded bg-white/80" /></div></div>),
        products: (<div className="flex h-full items-center justify-center gap-1.5 px-3">{[1,2,3].map(i => <div key={i} className="h-10 w-9 rounded border border-slate-200 bg-white p-1"><div className="h-4 w-full rounded bg-slate-100" /><div className="mt-0.5 h-1 w-full rounded bg-slate-200" /><div className="mt-0.5 h-1 w-4 rounded bg-blue-300" /></div>)}</div>),
        booking_service: (<div className="flex h-full items-center gap-2 px-3"><div className="h-8 w-10 rounded bg-slate-200" /><div className="flex-1 space-y-0.5"><div className="h-1.5 w-12 rounded bg-slate-300" /><div className="h-1 w-8 rounded bg-slate-200" /><div className="mt-1 h-2 w-8 rounded bg-blue-300" /></div></div>),
        about_hero: (<div className="flex h-full items-center justify-center"><div className="text-center"><div className="mx-auto h-2 w-20 rounded bg-slate-300" /><div className="mx-auto mt-1 h-1.5 w-28 rounded bg-slate-200" /></div></div>),
        journey: (<div className="flex h-full items-center gap-2 px-3"><div className="flex-1 space-y-1"><div className="h-1.5 w-14 rounded bg-slate-300" /><div className="h-1 w-20 rounded bg-slate-200" /></div><div className="flex gap-2">{[1,2].map(i => <div key={i} className="text-center"><div className="h-2 w-5 rounded bg-blue-300" /><div className="mt-0.5 h-0.5 w-6 rounded bg-slate-200" /></div>)}</div></div>),
        values: (<div className="flex h-full items-center justify-center gap-1.5 px-3">{[1,2,3].map(i => <div key={i} className="h-8 w-8 rounded border border-slate-200 bg-white p-1"><div className="h-2 w-2 rounded-full bg-blue-200" /><div className="mt-1 h-1 w-full rounded bg-slate-200" /></div>)}</div>),
        expertise: (<div className="flex h-full items-center gap-2 px-3"><div className="h-8 w-12 rounded bg-slate-600" /><div className="flex-1 space-y-0.5">{[1,2,3].map(i => <div key={i} className="flex items-center gap-1"><div className="h-1 w-1 rounded-full bg-blue-400" /><div className="h-1 w-10 rounded bg-slate-500" /></div>)}</div></div>),
        rich_text: (<div className="flex h-full items-center justify-center px-3"><div className="w-full space-y-1"><div className="h-1.5 w-20 rounded bg-slate-300" /><div className="h-1 w-full rounded bg-slate-200" /><div className="h-1 w-5/6 rounded bg-slate-200" /></div></div>),
        custom_html: (<div className="flex h-full items-center justify-center px-3"><div className="font-mono text-[8px] text-slate-400">&lt;div&gt;...&lt;/div&gt;</div></div>),
    };
    return (
        <div className={'h-16 w-full shrink-0 ' + (bg[type] || 'bg-slate-50 border-b')}>
            {previews[type] || <div className="flex h-full items-center justify-center"><div className="h-3 w-16 rounded bg-slate-200" /></div>}
        </div>
    );
}
